/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_fhnw_prcpp_jni_Matrix */

#ifndef _Included_ch_fhnw_prcpp_jni_Matrix
#define _Included_ch_fhnw_prcpp_jni_Matrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_fhnw_prcpp_jni_Matrix
 * Method:    multiplyC
 * Signature: ([D[D[DIII)V
 */
JNIEXPORT void JNICALL Java_ch_fhnw_prcpp_jni_Matrix_multiplyC
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
